version: 2.1
orbs:
  node: circleci/node@5.1.0

workflows:
  test:
    jobs:
      - node/test: 
          test-results-for: jest
          test-results-path: junit.xml

  deploy:
    jobs:
      - node/run:
          npm-run: build
      - publish:
          name: Publish to NPM
            command: |
                npm set //registry.npmjs.org/:_authToken=$NPM_TOKENi
                npm publish
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
